[placeholders.example]
type = "text"
prompt = "example input test case"
regex = "[^ ]"

[placeholders.example_eq]
type = "string"
prompt = "example input equal to"
regex = "[0-9]+"

[placeholders.input]
type = "text"
prompt = "main puzzle input"
regex = "[^ ]"
