[package]
name = "day16"
authors = ["mirsella <mirsella@protonmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

grid = { git = "https://github.com/becheran/grid" }
itertools = "0.12.0"
